name: Second Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4

        - name: permission
          run: chmod +x ascii.sh
            
        - name: Install ASCII program
          run: ./ascii.sh