name: multiline Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4

        - name: Multiline command
          run: |
             echo "Hello Guys, I am at Google Now"
             ls -lrth
             cat README.md